### ISSUE TITLE
No Authrization on android

### ISSUE THREAD

**Issue by imasif** [Wachu985/flutter_wireguard_vpn#11]
I am not getting any Authorization modal popup as before, and I cannot scan (Activate VPN) any more, here is the what I find while start scanning on the console:
```
/WireGuard/GoBackend(22086): Bringing tunnel SPYED_VPN UP
E/MainActivity(22086): handleSetState - BackendException - ERROR - VPN_NOT_AUTHORIZED
E/flutter (22086): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'ConnectionException'
E/flutter (22086): #0      MethodChannelWireguardVpn.changeStateParams (package:wireguard_vpn/wireguard_vpn_method_channel.dart:24:7)
E/flutter (22086): <asynchronous suspension>
E/flutter (22086): #1      _PageState._activateVpn (package:interceptor_mobile/scan.dart:297:21)
E/flutter (22086): <asynchronous suspension>
```

Can you find the issue?

**Comment by imasif** [comment]
This issue started, after installing `Flutter_Stripe`
