### ISSUE TITLE
IOS version?

### ISSUE THREAD

**Issue by hinetapora** [Wachu985/flutter_wireguard_vpn#5]
Thanks for the great work - has anyone go the ios working?

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Instance of 'ConnectionException'
#0      MethodChannelWireguardVpn.changeStateParams (package:wireguard_vpn/wireguard_vpn_method_channel.dart:24:7)
<asynchronous suspension>
#1      _MyAppState._activateVpn (package:my_flutter_app/main.dart:82:9)
<asynchronous suspension>

**Comment by hinetapora** [comment]
Lol there is no IOS version! :) Well not yet anyway.  The android version runs just fine in emulator S23 API 34 but you must add a PSK to the peer config if you dont have it there already.  wg pskgen will create a complaint key which you save to the server peer config and the main.dart e.g.:   final String presharedKey = 'eiTPIpnRi8er333g275HxUG...4I5kwR52sUVF3zfuI=';

**Comment by bugrevealingbme** [comment]
sad

**Comment by Wachu985** [comment]
Regarding the iOS version, the package does not currently have one, and I lack both the resources and the knowledge to develop it at this time. However, please remember that you are welcome to contribute to the package whenever you wish. Your help would be greatly appreciated.

**Comment by Jin-Django** [comment]
How can i get presharedKey ? i'm new to wg and i just created an account from ProtonVPN for testing but I didn't see presharedKey after created wireguard configuration
